spring.application.name=quantity-service

server.port=8082

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# DB Config
spring.datasource.url=jdbc:mysql://localhost:3306/quantity
spring.datasource.username=root
spring.datasource.password=Guddan#@02

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true